# Generated by Django 2.0.2 on 2018-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170416_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_manager',
            field=models.BooleanField(default=False, help_text="Designates whether the user can interact with other user's information.", verbose_name='manager status'),
        ),
    ]
