# Generated by Django 2.0.2 on 2018-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_main_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_password_code',
            field=models.PositiveIntegerField(default=0, verbose_name='reset code'),
        ),
    ]
