# Generated by Django 2.0.2 on 2018-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_reset_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_code_expiry',
            field=models.PositiveIntegerField(default=0, verbose_name='code expire'),
        ),
    ]
