# Generated by Django 2.0.2 on 2018-07-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_password_code_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password_code_expiry',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reset_password_code',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='password_code_expiry',
            field=models.PositiveIntegerField(default=0, verbose_name='code expire'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='reset_password_code',
            field=models.PositiveIntegerField(default=0, verbose_name='reset code'),
        ),
    ]
