# Generated by Django 2.0.2 on 2018-07-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180703_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='password_code_expiry',
        ),
    ]
