# Generated by Django 2.0.2 on 2018-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmember',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='clientmember',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
    ]
