# Generated by Django 2.0.2 on 2018-05-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20180506_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmember',
            name='base_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to='account.Account', verbose_name='Client'),
        ),
    ]
