# Generated by Django 2.0.2 on 2018-06-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20180501_2135'),
        ('consumer', '0003_auto_20180515_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmember',
            name='last_appt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_appoinment', to='service.Service', verbose_name='Last Appointment'),
        ),
    ]
