# Generated by Django 2.0.2 on 2018-06-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_clientmember_last_appt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmember',
            name='last_appt',
        ),
    ]
