# Generated by Django 2.0.2 on 2018-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityForDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=15, verbose_name='Day of the week')),
                ('scheduled_start', models.TimeField(default='07:00', verbose_name='start time of day')),
                ('scheduled_end', models.TimeField(default='17:00', verbose_name='end time of day')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('cancelled', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('meeting_number', models.PositiveIntegerField(default=1)),
                ('rescheduled_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client Event',
                'verbose_name_plural': 'Client Events',
                'ordering': ['start', 'client_service'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.CharField(max_length=20, verbose_name='Staff Activity')),
                ('work_related', models.BooleanField(default=False)),
                ('no_longer_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Staff Event',
                'verbose_name_plural': 'Staff Events',
                'ordering': ['start', 'staff_activity'],
            },
        ),
    ]
