# Generated by Django 2.0.2 on 2018-04-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('staffer', '0001_initial'),
        ('event', '0001_initial'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffevent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_staff_event', to='staffer.StaffMember', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='staffevent',
            name='staff_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_activity', to='event.StaffActivityType', verbose_name='Staff Activity Options'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='client_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_service', to='service.Service'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_client_event', to='staffer.StaffMember', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='user_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to='consumer.ClientMember', verbose_name='Client Member'),
        ),
        migrations.AddField(
            model_name='availabilityforday',
            name='avail_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_services', to='service.Service', verbose_name='Available Services'),
        ),
        migrations.AddField(
            model_name='availabilityforday',
            name='staff_availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_availability', to='staffer.StaffMember', verbose_name='Staff Availability For Day'),
        ),
    ]
