# Generated by Django 2.0.2 on 2018-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180405_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientevent',
            name='rescheduled_number',
        ),
        migrations.AddField(
            model_name='clientevent',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
