# Generated by Django 2.0.2 on 2018-04-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180424_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='client_mood',
            field=models.CharField(choices=[('Very Pleased', 'Very Pleased'), ('Satisfied', 'Satisfied'), ('Dissatisfied', 'Dissatisfied'), ('Upset', 'Upset')], default='Satisfied', max_length=20, verbose_name="client's mood"),
        ),
    ]
