# Generated by Django 2.0.2 on 2018-04-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_clientevent_client_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientevent',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='clientevent',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='clientevent',
            name='no_show',
        ),
        migrations.AddField(
            model_name='clientevent',
            name='status',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Attended', max_length=20, verbose_name='appointment status'),
        ),
    ]
