# Generated by Django 2.0.2 on 2018-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180424_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='client_mood',
            field=models.CharField(choices=[('Not Complete', 'Not Complete'), ('Very Pleased', 'Very Pleased'), ('Satisfied', 'Satisfied'), ('Dissatisfied', 'Dissatisfied'), ('Upset', 'Upset')], default='Not Complete', max_length=20, verbose_name="client's mood"),
        ),
        migrations.AlterField(
            model_name='clientevent',
            name='status',
            field=models.CharField(choices=[('Not Complete', 'Not Complete'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Not Complete', max_length=20, verbose_name='appointment status'),
        ),
    ]
