# Generated by Django 2.0.2 on 2018-04-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0002_auto_20180405_1530'),
        ('event', '0006_auto_20180425_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityforday',
            name='avail_services',
        ),
        migrations.RemoveField(
            model_name='availabilityforday',
            name='staff_availability',
        ),
        migrations.AddField(
            model_name='availabilityforday',
            name='staff_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_availability', to='staffer.StaffMember', verbose_name='Staff Member'),
            preserve_default=False,
        ),
    ]
