# Generated by Django 2.0.2 on 2018-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0002_auto_20180405_1530'),
        ('event', '0007_auto_20180426_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityforday',
            options={'ordering': ['day', 'staff_member'], 'verbose_name': "Staff's Scheduled Hours For Day Of The Week", 'verbose_name_plural': "Staff's Scheduled Hours For Days Of The Week"},
        ),
        migrations.AddField(
            model_name='staffevent',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityforday',
            unique_together={('staff_member', 'day')},
        ),
    ]
