# Generated by Django 2.0.2 on 2018-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20180430_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='origin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
