# Generated by Django 2.0.2 on 2018-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20180430_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='second_part_pk',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
