# Generated by Django 2.0.2 on 2018-05-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20180429_1106'),
        ('staffer', '0002_auto_20180405_1530'),
        ('consumer', '0001_initial'),
        ('event', '0013_clientevent_second_part_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondPartEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('client_service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_part_client_service', to='service.Service')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_part_staff_for_client_event', to='staffer.StaffMember', verbose_name='Staff Member')),
                ('user_client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_part_user_client', to='consumer.ClientMember', verbose_name='Client Member')),
            ],
            options={
                'verbose_name': 'Second Part',
                'verbose_name_plural': 'Second Parts',
                'ordering': ['start'],
            },
        ),
        migrations.RemoveField(
            model_name='clientevent',
            name='second_part',
        ),
        migrations.RemoveField(
            model_name='clientevent',
            name='second_part_pk',
        ),
        migrations.AddField(
            model_name='clientevent',
            name='second_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_client_second_event', to='event.SecondPartEvent', verbose_name='Second Part Event'),
        ),
    ]
