# Generated by Django 2.0.2 on 2018-05-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20180501_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='second_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_client_second_event', to='event.SecondPartEvent', verbose_name='Second Part Event'),
        ),
    ]
