# Generated by Django 2.0.2 on 2018-05-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20180501_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='client_mood',
            field=models.CharField(choices=[('Not Complete', 'Not Complete'), ('Very Pleased', 'Very Pleased'), ('Satisfied', 'Satisfied'), ('Dissatisfied', 'Dissatisfied'), ('Upset', 'Upset'), ('NA', 'N/A')], default='Not Complete', max_length=20, verbose_name="client's mood"),
        ),
    ]
