# Generated by Django 2.0.2 on 2018-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20180504_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityforday',
            name='day',
            field=models.CharField(max_length=15, verbose_name='Day of the week'),
        ),
    ]
