# Generated by Django 2.0.2 on 2018-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20180505_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityforday',
            name='scheduled_end',
            field=models.CharField(max_length=15, verbose_name='end time of day'),
        ),
        migrations.AlterField(
            model_name='availabilityforday',
            name='scheduled_start',
            field=models.CharField(max_length=15, verbose_name='start time of day'),
        ),
    ]
