# Generated by Django 2.0.2 on 2018-05-15 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20180506_1420'),
        ('event', '0022_auto_20180506_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='staff_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_client', to='consumer.ClientMember', verbose_name='Staff Client'),
        ),
        migrations.AlterField(
            model_name='clientevent',
            name='user_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to='consumer.ClientMember', verbose_name='Client Member'),
        ),
    ]
