# Generated by Django 2.0.2 on 2018-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_auto_20180515_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondpartevent',
            name='user_client',
            field=models.CharField(blank=True, max_length=50, verbose_name='Client'),
        ),
    ]
