# Generated by Django 2.0.2 on 2018-05-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20180515_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='staff_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_client', to='staffer.StaffMember', verbose_name='Staff Client'),
        ),
    ]
