# Generated by Django 2.0.2 on 2018-05-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20180515_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientevent',
            name='client_service',
            field=models.ForeignKey(limit_choices_to={'service_no_longer_available': False}, on_delete=django.db.models.deletion.CASCADE, related_name='client_service', to='service.Service'),
        ),
    ]
