# Generated by Django 2.0.2 on 2018-06-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_auto_20180601_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityforday',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_availabilityiii', to='staffer.StaffMember', verbose_name='Staff Member'),
        ),
    ]
