# Generated by Django 2.0.2 on 2018-06-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20180601_2321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabilityforday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='availabilityforday',
            name='staff_member',
        ),
        migrations.DeleteModel(
            name='AvailabilityForDay',
        ),
    ]
