# Generated by Django 2.0.2 on 2018-04-05 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('unit_type', models.CharField(choices=[('minute', 'Minute'), ('occurence', 'Occurence')], default='minute', max_length=40)),
                ('units', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost per Unit')),
                ('service_no_longer_available', models.BooleanField(default=False)),
                ('service_branch_description', models.CharField(max_length=130, unique=True, verbose_name='service branch description')),
            ],
            options={
                'verbose_name': 'Service Branch Description',
                'verbose_name_plural': 'Service Branch Description',
                'ordering': ['service_branch_description'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('unit_type', models.CharField(choices=[('minute', 'Minute'), ('occurence', 'Occurence')], default='minute', max_length=40)),
                ('units', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost per Unit')),
                ('service_no_longer_available', models.BooleanField(default=False)),
                ('retail_service', models.CharField(max_length=130, unique=True, verbose_name='retail service')),
                ('service_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_branch', to='service.Branch', verbose_name='Service Branch Description')),
            ],
            options={
                'verbose_name': 'Retail Service',
                'verbose_name_plural': 'Retail Services',
                'ordering': ['service_branch', 'retail_service'],
            },
        ),
    ]
