# Generated by Django 2.0.2 on 2018-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='can_overlap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='overlap_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
