# Generated by Django 2.0.2 on 2018-04-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180423_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_branch', to='service.Branch', verbose_name='Service Branch'),
        ),
    ]
