# Generated by Django 2.0.2 on 2018-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180423_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
