# Generated by Django 2.0.2 on 2018-04-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180424_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='popular',
        ),
    ]
