# Generated by Django 2.0.2 on 2018-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_branch_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='overlap_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='start of overlap from start in minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='overlap_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='overlap duration in minutes'),
        ),
    ]
