# Generated by Django 2.0.2 on 2018-04-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20180424_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='can_overlap',
        ),
    ]
