# Generated by Django 2.0.2 on 2018-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_service_can_overlap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='overlap_from',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='minutes from start for the start of overlap'),
        ),
        migrations.AlterField(
            model_name='service',
            name='overlap_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='overlap duration in minutes'),
        ),
    ]
