# Generated by Django 2.0.2 on 2018-04-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20180429_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit_type',
        ),
    ]
