# Generated by Django 2.0.2 on 2018-04-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20180429_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='units',
            new_name='minutes',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='units',
            new_name='minutes',
        ),
    ]
