# Generated by Django 2.0.2 on 2018-04-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='base_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_account', to='account.Account', verbose_name='Staff Member'),
        ),
    ]
