# Generated by Django 2.0.2 on 2018-05-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20180501_2135'),
        ('staffer', '0002_auto_20180405_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='skill_set',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='service.Service', verbose_name='skills'),
        ),
    ]
