# Generated by Django 2.0.2 on 2018-05-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0003_auto_20180502_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='skills',
        ),
    ]
