# Generated by Django 2.0.2 on 2018-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20180501_2135'),
        ('staffer', '0004_remove_staffmember_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='skill_set',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='skill_set',
            field=models.ManyToManyField(blank=True, related_name='staff_skills', to='service.Service'),
        ),
    ]
