# Generated by Django 2.0.2 on 2018-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0006_auto_20180506_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_manager',
            field=models.BooleanField(default=False, help_text="Designates whether the user can interact with other user's information.", verbose_name='manager status'),
        ),
    ]
