# Generated by Django 2.0.2 on 2018-05-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0007_staffmember_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='is_manager',
        ),
    ]
