# Generated by Django 2.0.2 on 2018-05-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0008_remove_staffmember_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='base_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_account', to='account.Account', verbose_name='Staff Member'),
        ),
    ]
