# Generated by Django 2.0.2 on 2018-06-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0010_auto_20180601_2241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabilityforday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='availabilityforday',
            name='staff_member',
        ),
        migrations.DeleteModel(
            name='AvailabilityForDay',
        ),
    ]
