# Generated by Django 2.0.2 on 2018-04-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='initial_password',
        ),
    ]
