# Generated by Django 2.0.2 on 2018-04-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0002_remove_company_initial_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alert',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='company alert'),
        ),
        migrations.AddField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='company bio'),
        ),
        migrations.AddField(
            model_name='company',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='caption'),
        ),
    ]
