# Generated by Django 2.0.2 on 2018-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0006_auto_20180503_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='time_step',
            field=models.PositiveIntegerField(default=30, verbose_name='Schedule Time Step'),
        ),
    ]
