# Generated by Django 2.0.2 on 2018-05-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0009_auto_20180503_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='end',
            field=models.CharField(max_length=15, verbose_name='end time of day'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='start',
            field=models.CharField(max_length=15, verbose_name='start time of day'),
        ),
    ]
