# Generated by Django 2.0.2 on 2018-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0011_auto_20180506_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='appt_step',
            field=models.PositiveIntegerField(default=30, verbose_name='Appointment Select Options Time Step'),
        ),
        migrations.AlterField(
            model_name='company',
            name='work_step',
            field=models.PositiveIntegerField(default=30, verbose_name='Schedule for Day Time Step'),
        ),
    ]
