# Generated by Django 2.0.2 on 2018-05-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortium', '0012_auto_20180510_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('name', models.CharField(max_length=40)),
                ('day', models.DateField()),
                ('can_work', models.BooleanField(default=False, verbose_name='Overtime Optional')),
            ],
            options={
                'verbose_name': 'Company Holiday',
                'verbose_name_plural': 'Company Holidays',
                'ordering': ['day'],
            },
        ),
    ]
